version: '3.8'

services:
  postgres-db:
    container_name: postgres-db
    image: postgres:alpine
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
      POSTGRES_DB: "agenda"
      TZ: "America/Sao_Paulo"
    ports:
      - "15432:5432"
    networks:
      - docker-network
    restart: always

  agenda-service:
    container_name: agenda-service
    image: agenda-service-api:latest
    environment:
      SERVER_PORT: 3000
      SPRING_PROFILES_ACTIVE: dev
      TZ: "America/Sao_Paulo"
    ports:
      - "80:3000"
    depends_on:
      - postgres-db
    networks:
      - docker-network
    deploy:
      resources:
        limits:
          memory: 700M
        reservations:
          memory: 700M
    restart: always

networks:
  docker-network:
    driver: bridge